mod = "mod4"
alt = "mod1"

shell = "fish"
terminal = "alacritty"
browser = "firefox"
home = "/home/tusqasi/"
launcher = "rofi -show combi -combi-modi 'drun,run,window' -modi combi"
startup_script = "/home/tusqasi/scripts/startup.sh"
file_manager = "pcmanfm"
