abbr c="clear"
abbr cfg="/usr/bin/git --git-dir=/home/tusqasi/.cfg/ --work-tree=/home/tusqasi"
abbr e="~/scripts/edit_configs.sh"
abbr inst="sudo pacman -S"
abbr n="nvim"
abbr p="ping google.com"
abbr pinst="pip install"
abbr py="python"
abbr q="exit"
abbr rmpkg="sudo pacman -R"
abbr s="sudo"
abbr sn="sudoedit"
abbr updt="sudo pacman -Syu"
abbr v.="vifm ./"
abbr vp="nsxiv"
