[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xff0099"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xff0000"
white = "0xd0d0d0"
yellow = "0xff0099"

[colors.primary]
background = "0x000000"
foreground = "0xd0d0d0"

[env]
TERM = "xterm-256color"

[font]
size = 9

[font.offset]
x = 0
y = 0

[schemes.dracula.bright]
black = "#575b70"
blue = "#caa9fa"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff92d0"
red = "#ff6e67"
white = "#e6e6e6"
yellow = "#f4f99d"

[schemes.dracula.normal]
black = "#000000"
blue = "#caa9fa"
cyan = "#8be9fd"
green = "#50fa7b"
magenta = "#ff79c6"
red = "#ff5555"
white = "#bfbfbf"
yellow = "#f1fa8c"

[schemes.dracula.primary]
background = "#282a36"
foreground = "#f8f8f2"

[schemes.gruvbox-dark.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[schemes.gruvbox-dark.cursor]
cursor = "CellForeground"
text = "CellBackground"

[schemes.gruvbox-dark.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[schemes.gruvbox-dark.primary]
background = "#282828"
bright_foreground = "#f9f5d7"
dim_foreground = "#f2e5bc"
foreground = "#fbf1c7"

[schemes.gruvbox-dark.selection]
background = "CellForeground"
text = "CellBackground"

[schemes.gruvbox-dark.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[schemes.gruvbox-light.bright]
black = "#928374"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#3c3836"
yellow = "#b57614"

[schemes.gruvbox-light.normal]
black = "#fbf1c7"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#7c6f64"
yellow = "#d79921"

[schemes.gruvbox-light.primary]
background = "#f2e5bc"
foreground = "#3c3836"

[schemes.isotope.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xff0000"
white = "0xffffff"
yellow = "0xff0099"

[schemes.isotope.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xff0000"
white = "0xd0d0d0"
yellow = "0xff0099"

[schemes.isotope.primary]
background = "0x000000"
foreground = "0xd0d0d0"

[schemes.lantern.bright]
black = "#793513"
blue = "#638987"
cyan = "#7F9587"
green = "#959433"
magenta = "#BF64BC"
red = "#E1471E"
white = "#e35b15"
yellow = "#F5A927"

[schemes.lantern.cursor]
cursor = "#e4cbb3"
text = "#291812"

[schemes.lantern.dim]
black = "#442212"
blue = "#3E7C86"
cyan = "#5A8887"
green = "#708632"
magenta = "#9A56BC"
red = "#BB3A1D"
white = "#ae4814"
yellow = "#D09B27"

[schemes.lantern.normal]
black = "#5e2b13"
blue = "#4395a3"
cyan = "#66a4a4"
green = "#82a23a"
magenta = "#b666e6"
red = "#e04220"
white = "#c85115"
yellow = "#fabc2c"

[schemes.lantern.primary]
background = "#291812"
foreground = "#c85115"

[schemes.lantern.selection]
background = "#4395a3"
text = "#291812"

[schemes.solarized-dark.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized-dark.cursor]
cursor = "#839496"
text = "#002b36"

[schemes.solarized-dark.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized-dark.primary]
background = "#002b36"
foreground = "#839496"

[schemes.solarized-light.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized-light.cursor]
cursor = "#657b83"
text = "#fdf6e3"

[schemes.solarized-light.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized-light.primary]
background = "#fdf6e3"
foreground = "#657b83"

[scrolling]
history = 5000
multiplier = 3

[window]
decorations = "None"

[window.padding]
x = 5
y = 5
